name: Validate

on:
  push:
    branches:
      - "main"

jobs:
  Windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: create .env
        run: Copy-Item ".\.env_example" -Destination ".\.env"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Binary
        run: flutter build windows

  Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: create .env
        run: cp ./.env_example ./.env

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: install needed dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Doctor
        run: flutter doctor

      - name: Binary
        run: flutter build linux --release

      - name: LDD
        run: ldd build/linux/x64/release/bundle/myWitWallet

  MacOs:
    environment: Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: create .env
        run: cp ./.env_example ./.env

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Binary
        run: flutter build macos --debug

  Android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: create .env
        run: cp ./.env_example ./.env

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Binary
        run: flutter build appbundle --debug

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: 'android'

      - name: Run Tests
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'test'
          subdirectory: 'android'

  IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: create .env
        run: cp ./.env_example ./.env

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Binary
        run: flutter build ios --release --no-codesign